services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
     - ./frontend:/app
     - /app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - start-dev
      - --features=preview
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=NotesDB
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build: 
      context: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NotesDB
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
  keycloak-db-data:
